// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOME_LdXOSFG4ZuiFVtcmCle9fj6XZTqA',
    appId: '1:929236157058:web:b58f051c5887d13f59ea9b',
    messagingSenderId: '929236157058',
    projectId: 'socialmedia-d1bed',
    authDomain: 'socialmedia-d1bed.firebaseapp.com',
    storageBucket: 'socialmedia-d1bed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPendW-IuyP1QEOswLotRnoeOY8Qs2Rb0',
    appId: '1:929236157058:android:c78d87fd51d4b88b59ea9b',
    messagingSenderId: '929236157058',
    projectId: 'socialmedia-d1bed',
    storageBucket: 'socialmedia-d1bed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_Xa353rnrj9JWdKfPhvc_t3EQ3U92Zuo',
    appId: '1:929236157058:ios:9d15ae7c15d3e1af59ea9b',
    messagingSenderId: '929236157058',
    projectId: 'socialmedia-d1bed',
    storageBucket: 'socialmedia-d1bed.appspot.com',
    iosBundleId: 'com.example.socialmedia',
  );
}
